baseURL = "https://kusandri.id/"
theme="hugo-theme-minos"
title = "Kus Andriadi"
enableRobotsTXT=true

[Author]
    name = "Kus Andriadi"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 1

[params.author]
	name = "Kus Andriadi"
	gravatar = "me@kusandriadi.com"
	github = "kusandriadi"

[params]
	showShareIcons=true
	canonifyurls = true

[permalinks]
  posts = "/:section/:title/"

[sitemap]
  ChangeFreq = "weekly"
  Priority = "0.5"
  filename = "sitemap.xml"