baseURL = "https://kusandriadi.com/"
theme="hugo-theme-minos"
title = "Kus Andriadi"
enableRobotsTXT=true
googleAnalytics = "UA-141670233-1"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Resources"
  identifier = "resources"
  url = "#"
  weight = 2

[[menu.main]]
  name = "Computer Science"
  parent = "resources"
  url = "https://www.kusandriadi.com/cs"
  weight = 1

[[menu.main]]
  name = "AI Blog"
  parent = "resources"
  url = "https://www.kusandriadi.com/ai-blog"
  weight = 2

[[menu.main]]
  name = "Jadwal Sholat Indonesia"
  parent = "resources"
  url = "https://www.kusandriadi.com/salat-time"
  weight = 3

[[menu.main]]
  name = "Elcompia"
  parent = "resources"
  url = "https://www.kusandriadi.com/elcompia"
  weight = 4

[params.author]
	name = "Kus Andriadi"
	github = "kusandriadi"

[params]
	showShareIcons=true
	canonifyurls = true
	enableEmoji=true

[permalinks]
  posts = "/:section/:title/"

[sitemap]
  ChangeFreq = "weekly"
  Priority = "0.5"
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
