baseURL = "https://kusandriadi.github.io/"
theme="hugo-theme-minos"
title = "Kus Andriadi"

[Author]
    name = "Kus Andriadi"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 1

[params.author]
	name = "Kus Andriadi"
	gravatar = "me@kusandriadi.com"
	github = "kusandriadi"

[params]
	showShareIcons=false